### ISSUE TITLE
Workable solution, but you can try to come up with your own algorithm without regulars :)

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/os-serialization-and-file-system#1]
https://github.com/NikitaZhukovsky/os-serialization-and-file-system/blob/e491e6f592adda038c5797a3d9cd8d71954904e9/Task_%239_6/find_numbers.py#L9-L10

**Comment by NikitaZhukovsky** [comment]
But it looks nice and there are fewer lines of code
