### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/os-serialization-and-file-system#2]
https://github.com/NikitaZhukovsky/os-serialization-and-file-system/blob/e491e6f592adda038c5797a3d9cd8d71954904e9/Task_%239_8/employee.py#L122-L124
![Снимок экрана 2024-01-15 в 15 36 37](https://github.com/NikitaZhukovsky/os-serialization-and-file-system/assets/44698380/1ae339f7-4bb0-4569-aadc-a1a26646ab56)

**Comment by NikitaZhukovsky** [comment]
Fixed it
