### ISSUE TITLE
Something wrong......... add user input error handling. Invalid (negative e.g.) values should not be acceptable

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/os-serialization-and-file-system#3]
https://github.com/NikitaZhukovsky/os-serialization-and-file-system/blob/e491e6f592adda038c5797a3d9cd8d71954904e9/Task_%239_8/employee.py#L122-L124
![Снимок экрана 2024-01-15 в 15 38 38](https://github.com/NikitaZhukovsky/os-serialization-and-file-system/assets/44698380/5876ca7d-59fa-4356-b907-8d3c0fff7282)

**Comment by NikitaZhukovsky** [comment]
Fixed everything)
