### ISSUE TITLE
Data storage format mismatch

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/os-serialization-and-file-system#4]
https://github.com/NikitaZhukovsky/os-serialization-and-file-system/blob/e491e6f592adda038c5797a3d9cd8d71954904e9/Task_%239_8/employee.py#L122-L124
![Снимок экрана 2024-01-15 в 15 41 59](https://github.com/NikitaZhukovsky/os-serialization-and-file-system/assets/44698380/0bb9be4e-f9e8-4edf-92ec-7ecb98d38446)

**Comment by NikitaZhukovsky** [comment]
And this fixed it
