### ISSUE TITLE
A little error handling would be nice

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/os-serialization-and-file-system#5]
https://github.com/NikitaZhukovsky/os-serialization-and-file-system/blob/e491e6f592adda038c5797a3d9cd8d71954904e9/Task_%239_8/employee.py#L22-L34
![Снимок экрана 2024-01-24 в 14 42 26](https://github.com/NikitaZhukovsky/os-serialization-and-file-system/assets/44698380/20873ead-941a-4d2e-969a-5f1ed393972f)

**Comment by NikitaZhukovsky** [comment]
Fixed this problem
